### ISSUE TITLE
Stats only update once 

### ISSUE THREAD

**Issue by rooneybuk** [pdinklag/MinecraftStats#104]
I’ve configured everything in including cron and everything populates fine but any subsequent executes manual or through cron don’t update the site and there is not error message

**Comment by pdinklag** [comment]
Hm, we'll need to figure out if there's really no update happening or if there's maybe some browser cache issues going on. "No error message" can mean everything worked - or nothing was done, maybe I need to change that.

What exactly do you mean by "don't update the site", are you referring to the "Last update" text on the top right of the page? The near-obvious question: did you try clearing your browser cache for the site and reload? I believe I took measures against the data files being cached, so we could consider this a bug if this was the problem.

How about the server-side: does the last modified time of the files (e.g. `data/summary.json.gz`) change, or does that also not get updated at all?

**Comment by rooneybuk** [comment]
Hi Patrick, 

it seem like the files dont get updated.

`root@mineos-tkldev .../MinecraftStats/data# ls -alh   
total 56K
drwxr-xr-x 7 root root 4.0K May  1 19:17 .
drwxr-xr-x 9 root root 4.0K May  1 19:17 ..
drwxr-xr-x 2 root root 4.0K May  1 19:17 events
drwxr-xr-x 2 root root 4.0K May  1 19:17 playercache
drwxr-xr-x 2 root root 4.0K May  1 19:17 playerdata
drwxr-xr-x 2 root root 4.0K May  1 19:17 playerlist
-rw-r--r-- 1 root root 1.1K May  1 21:23 players.json
drwxr-xr-x 2 root root  12K May  1 19:17 rankings
-rwxr--r-- 1 root root 6.1K May  1 21:23 server-icon.png
-rw-r--r-- 1 root root 5.0K May  1 21:23 summary.json.gz
root@mineos-tkldev .../MinecraftStats/data# /usr/bin/python3 /var/www/html/MinecraftStats/update.py -s /var/games/minecraft/servers/Darkrealmz_S11/ --server-name "DarkRealmz"
updating profile for 59ed8fd3-1d29-4a4e-9e3b-74996c40f015 ...
updating profile for 3e750877-70e2-4009-b56e-2fc55ce29796 ...
updating profile for 39e1ed8f-0e01-424c-9d2f-7dfce10f515d ...
updating profile for ff09170d-794c-40ed-8d3f-6dbe155c2c25 ...
updating profile for e1867ed9-0ef8-4559-9b91-750c34104217 ...
updating profile for 7371beb3-82a4-4d7f-af9c-6ef933d2967b ...
stat "kill_bee" is not supported by server version 1952 (required: 2200)
stat "use_honey_bottle" is not supported by server version 1952 (required: 2200)
root@mineos-tkldev .../MinecraftStats/data# ls -alh
total 60K
drwxr-xr-x 8 root root 4.0K May  3 11:17 .
drwxr-xr-x 9 root root 4.0K May  1 19:17 ..
drwxr-xr-x 7 root root 4.0K May  3 11:17 data
drwxr-xr-x 2 root root 4.0K May  1 19:17 events
drwxr-xr-x 2 root root 4.0K May  1 19:17 playercache
drwxr-xr-x 2 root root 4.0K May  1 19:17 playerdata
drwxr-xr-x 2 root root 4.0K May  1 19:17 playerlist
-rw-r--r-- 1 root root 1.1K May  1 21:23 players.json
drwxr-xr-x 2 root root  12K May  1 19:17 rankings
-rwxr--r-- 1 root root 6.1K May  1 21:23 server-icon.png
-rw-r--r-- 1 root root 5.0K May  1 21:23 summary.json.gz
root@mineos-tkldev .../MinecraftStats/data# `

also I just want to say this is an awsome free tool :)

**Comment by pdinklag** [comment]
It actually is updating, and I see there was a `data` directory added in your `data` directory. It appears as though the updated files are in that nested `data` directory?

Try executing the script from the `.../MinecraftStats/` directory and not from within `data`, as it uses the current working directory to look for `data` and then works in there. Or was this only a mistake in the demonstration?

**Comment by pdinklag** [comment]
Closing due to lack of feedback,
