### ISSUE TITLE
Update Error with legit UUID

### ISSUE THREAD

**Issue by mechcalvin** [pdinklag/MinecraftStats#105]
I got this error:
`updating profile for af2bf8af-afce-4a8d-b5f5-1eaeb2ab160c ...
Traceback (most recent call last):
  File "update.py", line 347, in <module>
    name = player['name']
KeyError: 'name'
`
when do running update, this UUID is legit with correct name though, what is the reason?

**Comment by pdinklag** [comment]
That error message can't be from the latest version (compare [line 347](https://github.com/pdinklag/MinecraftStats/blob/a04b034d89ff7f49f9b5261cd821929140e8fffa/update.py#L347)). Can you updating to the current `master` and try again? There have been several fixes concerning Mojang API reading lately.

**Comment by pdinklag** [comment]
Closing due to lack of feedback.
