### ISSUE TITLE
Hide 'Last played' for all players

### ISSUE THREAD

**Issue by snurre0** [pdinklag/MinecraftStats#108]
Hi there!

Would it be possible to add an option to hide 'last played' for all players in all views? Or not save to the data files at all would also work.
I have no idea how easy or hard that would be to add, but that would be a greate feature for using it on a medium sized public server :) (at least ours).

Cheers!
/snurre

**Comment by pdinklag** [comment]
Hey!
The "last online" is only displayed in the Player List and when you view a player, right? That's an easy option to add, I guess.

**Comment by snurre0** [comment]
Yeah you're right, it's only displayed in the player lists and when viewing a single player :)
We don't really want to show off last online times, for the same reason as we're not allowing players to use commands like '/seen'.

I can always modify the web files myself, shouldn't be that hard really. Just wanted to ask if it's an easy addition.

**Comment by pdinklag** [comment]
Added the `client > showLastOnline` config option. Set it to `false` to hide the last online time.
