### ISSUE TITLE
certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by XXY233** [pdinklag/MinecraftStats#109]
updating profile for 4be74555-9336-3e4d-9bda-494979256918 ...
failed to update profile for 4be74555-9336-3e4d-9bda-494979256918
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>

All updates failed...

**Comment by pdinklag** [comment]
This is definitely not a MinecraftStats problem, but a problem in your Python setup.

I can only take a wild guess doing some basic research: are you running on a Mac OS X? If so, apparently Python doesn't come with certificates for whatever reason. Maybe try installing them manually according to this: https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate

If you're not on a Mac, I'm out of guesses.

**Comment by XXY233** [comment]
thank you for your reply, I think it might be a problem with Windows Server. Everything is normal on my own computer, sorry for wasting your time!

**Comment by pdinklag** [comment]
Maybe this helps: https://medium.com/@moreless/how-to-fix-python-ssl-certificate-verify-failed-97772d9dd14c
