### ISSUE TITLE
Error while running update.py player = players[uuid] KeyError: '00000000-0000-0000-0009-01fa34ab1ee1'

### ISSUE THREAD

**Issue by Leonardo-Fiori** [pdinklag/MinecraftStats#111]
```
updating profile for b65a4a00-589d-4259-8984-97c137d0b89b ...
updating profile for 473d9691-d6bf-4494-be13-2abf0b664f33 ...
updating profile for 2436b3f9-35e5-42d2-a1e0-c9b9bee14f70 ...
updating profile for ed5f3352-f43d-4113-8a64-b492b70331fc ...
updating profile for eaa87174-2d28-4666-aefe-988e08e8ab5f ...
updating profile for df713b79-1b7b-4e07-9bda-93cbe0a3b56e ...
Traceback (most recent call last):
  File "update.py", line 578, in <module>
    player = players[uuid]
KeyError: '00000000-0000-0000-0009-01fa34ab1ee1'
```
Update.py was running since 3/4 hours (i have many player files) and suddenly stopped with this error.

![image](https://user-images.githubusercontent.com/25549272/91583491-9767b380-e951-11ea-80fd-fc2d9a02e638.png)

Any idea? Some players login trough an amazing piece of sofware called Geyser Proxy, essentially it allows pocket edition (bedrock) players to play on java edition. The authentication happens on my Bungeecord Proxy Server Proxy, with a plugin called floodgate, that generates uuids for them. 

Paper version git-Paper-136
Python 3.7.3

**Comment by pdinklag** [comment]
It's OK that it fails getting data from the Mojang API because those IDs aren't real, but it shouldn't be crashing, that's a bug.

In general, though, I'm not supporting non-Mojang IDs right now. So once the crash is fixed, note that you will only see GUIDs in the browser instead of names. I might work on this to use the player cache names in the future for fake UUIDs, but I'll open another issue on that.

**Comment by Leonardo-Fiori** [comment]
Maybe as a quick fix before implementing non-mojang uuids, could we simply hide them? It would be really ugly to see uuids :)
Then, take your time, and consider implementing it properly if you want!

**Comment by pdinklag** [comment]
After having a look at the code, I'm a bit puzzled as to why this happens, because apparently what I said should already be happening.

I'll try to explain the problem in a nutshell: one of your bedrock players appears to be the best at some award and is supposed to appear on the front page, i.e., he is part of what I call the "summary". But there seems to be a contradiction I don't understand, because that player's ID seems to be unknown when the summary is created.

So I'd like to find out how exactly he got in the summary and how this can happen. I'll open a branch about it with a version of `update.py` that I'd like you to try, will get back here in a few minutes,

**Comment by pdinklag** [comment]
Could you please try running the `update.py` file in this branch: https://github.com/pdinklag/MinecraftStats/tree/debug_issue_111 

1. It should be printing some lines like "adding [UUID] to summary because ...", and I'd be interested in any line ending with "registered: False".
2. It should no longer crash like before, but instead write a line starting with "ERROR" that I'd also like to have.

This should hopefully get a working stat page for you (albeit maybe with some "???" entries for the players it failed on) and help me find out what exactly is wrong. :smiley:

**Comment by Leonardo-Fiori** [comment]
Just replaced update.py with your new version! Thanks for the quick edit :)
Testing... for now i see only stuff like `updating profile for 00000000-0000-0000-0009-01f5b2c1b32d`
waiting for it to get stuck on something!

**Comment by Leonardo-Fiori** [comment]
We got some true, some false and some ERROR, it is currently stuck, looks like it stopped without crash message:

`the hall of fame (registered: True)
adding b7a16f51-ba41-499c-9622-343717715ae0 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 5784c58a-4a3d-4c0f-ab23-98f650f3a7c7 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 00000000-0000-0000-0009-01fa34ab1ee1 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 279bc172-20d9-4779-adda-295412ef0381 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 4aca8cf0-e33e-4592-9257-67ebdf5ceb68 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 9c6c4d0d-fa4b-4450-afcc-b0fc46c85a62 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding ee2a8184-f46e-461f-bd9c-898c2a051e54 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding e9628dfd-092e-499e-904e-27550d63d232 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 49e3a7b1-c4ad-4a6b-bdf5-b3aa0808bd82 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 2e9973a0-24b5-4514-a935-927fea67c91b to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 01a8d490-4518-467d-83f9-898c8228e20d to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 75e3d5d0-1f85-40d1-8c66-645448430023 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 713e1330-31a5-43ea-99a0-4647e85990cc to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 2695db61-5a0e-4c38-a449-1186c9ff460e to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 00000000-0000-0000-0009-01f969987c50 to summary because they are part of                                                                                                                                    the hall of fame (registered: False)
adding 00000000-0000-0000-0009-01f2f5453662 to summary because they are part of                                                                                                                                    the hall of fame (registered: False)
adding 00000000-0000-0000-0009-01f1502dfa75 to summary because they are part of                                                                                                                                    the hall of fame (registered: False)
adding 3b3f9c3d-729a-4bca-9ce1-88d893dde0d9 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 40371e16-8efd-49ed-ba67-47fc9683863e to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding b4365842-a3ea-4e70-b31a-3f325e137a2a to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding a0c98e37-62ee-4810-bc49-741a5e513f1b to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 00000000-0000-0000-0009-01f226f17551 to summary because they are part of                                                                                                                                    the hall of fame (registered: False)
adding ef2b7b9d-4d0c-4e71-8dc2-df4443094ad6 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding ca7534b0-0d24-4bbe-a357-4d2e21f445bd to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding b613219e-23f2-4b79-b609-4282002d0e45 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding a4bd38ad-73a9-439b-afe9-d4f6ec974c01 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 62b4a7f8-6f88-45fa-ab16-85ad07541f60 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 89146369-9b90-4ea1-b6a0-e9019e7bdbaf to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 27a9c19a-2761-446c-96e2-707c5024daa1 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 1ba94033-a540-4c03-bd6b-3d1e0022d0fa to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding f3d8e4f2-0232-4325-947b-15c3cb1e1d74 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding f2c1dd90-ebd6-40e8-b669-9cd8b96f811c to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding f23d3fd4-a0e3-42d2-bd89-53e7bc246b52 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding f025b91d-be17-405d-8480-4c88bca3adcd to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding c771e655-c0e4-4fa6-8c7a-4a5a4c1b3053 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 6f5a0977-60d6-44a3-9bce-f6b2f3a3885e to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 56c688eb-bc8d-4b35-8bd8-8f40e4ca2d58 to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 19eeaa65-8245-4fb6-b49c-5b025ed10a6f to summary because they are part of                                                                                                                                    the hall of fame (registered: True)
adding 00000000-0000-0000-0009-01feaa9e5a20 to summary because they are part of                                                                                                                                    the hall of fame (registered: False)
adding 00000000-0000-0000-0009-01fe553c5f3c to summary because they are part of                                                                                                                                    the hall of fame (registered: False)
adding 00000000-0000-0000-0009-01fabf8a140e to summary because they are part of                                                                                                                                    the hall of fame (registered: False)
adding 00000000-0000-0000-0009-01f5934f9b5c to summary because they are part of                                                                                                                                    the hall of fame (registered: False)
ERRROR: 00000000-0000-0000-0009-01f969987c50 appears in the summary but is not r                                                                                                                                   egistered
ERRROR: 00000000-0000-0000-0009-01f226f17551 appears in the summary but is not r                                                                                                                                   egistered
ERRROR: 00000000-0000-0000-0009-01f5934f9b5c appears in the summary but is not r                                                                                                                                   egistered
ERRROR: 00000000-0000-0000-0009-01feaa9e5a20 appears in the summary but is not r                                                                                                                                   egistered
ERRROR: 00000000-0000-0000-0009-01fabf8a140e appears in the summary but is not r                                                                                                                                   egistered
ERRROR: 00000000-0000-0000-0009-01f1502dfa75 appears in the summary but is not r                                                                                                                                   egistered
ERRROR: 00000000-0000-0000-0009-01f2f5453662 appears in the summary but is not r                                                                                                                                   egistered
ERRROR: 00000000-0000-0000-0009-01fe553c5f3c appears in the summary but is not r                                                                                                                                   egistered
`

**Comment by pdinklag** [comment]
It should eventually have finished? If you have a lot of players, writing the client data may take some time.

Anyway, it's interesting to see that all and only the `000...` UUIDs are affected. You get no `(registered: False)` line above the snippet you sent, right? I'll have another look tomorrow and try to understand what's going on. Thanks for giving this a try!

**Comment by Leonardo-Fiori** [comment]
As you can see here, all the `registered: False` are 000... UUIDs, BUT not all 000... UUIDs are `registered: False`
For regular UUIDs, instead, they all look true

https://hastebin.com/ujalifosum.coffeescript

**Comment by Leonardo-Fiori** [comment]
Looks like it has completed, take a look here: https://www.peacefulvanilla.club/mcstats/index.html#player:00000000-0000-0000-0009-01fa34ab1ee1

This is a bedrock player, it recognizes it's name. Very strange. Other bedrock players are marked as ??? instead

**Comment by pdinklag** [comment]
> thanks for being so willing to fix issues

I'm slow adding new features, but fixing bugs is a priority on this project. :smile: 
It's good to see everything practically working well with the non-Mojang UUIDs.

But yes, the ??? players are the interesting ones and really have me puzzled. There must be stat files for them and somehow they got at least a bronze medal (rank 3 for some stat), but then again their UUID is not known, which is really a contradiction.

Is it possible for you to drop a stat file for one of those players, e.g., the `00000000-0000-0000-0009-01feaa9e5a20.json` file from the stats directory?

**Comment by pdinklag** [comment]
I also added some more debug output to `update.py`, there should now be some output lines starting with `DEBUG`. If any of those contains a UUID for which the script later prints an `ERROR`, that confirms the alleged contradiction. I still haven't quite figured why this could happen. 🤔

**Comment by Leonardo-Fiori** [comment]
> Is it possible for you to drop a stat file for one of those players, e.g., the 00000000-0000-0000-0009-01feaa9e5a20.json
 file from the stats directory?

You mean to upload here that file? Here it is! :)

[00000000-0000-0000-0009-01feaa9e5a20.zip](https://github.com/pdinklag/MinecraftStats/files/5145126/00000000-0000-0000-0009-01feaa9e5a20.zip)

**Comment by pdinklag** [comment]
The file looks totally fine to me, but when I put it on my server I can now reproduce your error exactly, so that's good news. 👍 
I'll have a look at this soon enough!

**Comment by pdinklag** [comment]
Turns out this happened when the Mojang API returns nothing for a UUID (e.g. because it is invalid) and there is also no `usercache.json` entry. These players will now be completely excluded, because since their user cache entry expired, they have been inactive in a good while anyway.

The contradiction I spoke of happened because even though the player was filtered later, their stats and rankings were processed, making them appear in rankings even though they were excluded. It should now be fixed.

**Comment by Leonardo-Fiori** [comment]
updated mojang.py and update.py taking the files from master branch, now the outputs look different but i think it worked! Don't see any "finish" or "process completed" message tho, but it looks done.

Take a look here: https://www.peacefulvanilla.club/mcstats/index.html#players:1

Are bedrock players still supposed to appear there now that i re-run the command? Looks that ??? players have disappeared, and that's nice

**Comment by pdinklag** [comment]
> updated mojang.py and update.py taking the files from master branch, now the outputs look different but i think it worked! Don't see any "finish" or "process completed" message tho, but it looks done.

Great!
There's indeed no "finish" message. My idea was initially that if there is no output, everything's fine, since Minecraft Stats is usually invoked in an automated manner and the process return code (0 = success) suffices.

> Are bedrock players still supposed to appear there now that i re-run the command? Looks that ??? players have disappeared, and that's nice

Yes, they are supposed to appear. I've had reports of people who wanted to see unregistered UUIDs before (probably cracked clients, though the reporters certainly won't admit), so I made Minecraft Stats look up the server's `usercache.json` file to get names for those players. Gettings their skins, however, is not possible.

What changed now is that players with unregistered UUIDs are ignored if there is no user cache entry, which happens if they have been away for a good while.

However, once they are in the Minecraft Stats database (in the `data` directory) with a valid name, they won't disappear unless you delete the `data` directory. Think of it as an extended user cache. 😃

**Comment by Leonardo-Fiori** [comment]
Wow, Amazing explaination! 😊 Thanks for all the good work. For now I will look into configuring a cronjob. How to get the return code zero tho?

**Comment by pdinklag** [comment]
Personally, I wrote a wrapper script that calls `update.py` and I registered a cronjob for the wrapper. I believe cron notifies you via the Linux internal mail daemon when a job failed (return code other than zero), but I'm no expert for cron, nor is this the place to discuss this. Feel free to contact me via mail or Discord.

**Comment by Leonardo-Fiori** [comment]
Sent you a request on ds! I am Hosom#3615

**Comment by Tyviebrock** [comment]
> It's OK that it fails getting data from the Mojang API because those IDs aren't real, but it shouldn't be crashing, that's a bug.
> 
> In general, though, I'm not supporting non-Mojang IDs right now. So once the crash is fixed, note that you will only see UUIDs in the browser instead of names. I might work on this to use the player cache names in the future for fake UUIDs, but I'll open another issue on that.

Hey, I'm wondering if you'd still be willing to add support for Geyser players.

Geyser players are formatted like this

"00000000-0000-0000-0009-0000083E49FC"

You'd have to trim down the UUID of the 
"00000000-0000-0000-" part 

and then covert the remainder "0009-0000083E49FC" to decimal (removing the remaining hyphen of course).

And then you can make a call to the public geyser API to https://api.geysermc.org/v2/xbox/gamertag/decimal_part_here for their xbox username.

As per their skins (if thats used)

You can use geysers API again and call
https://api.geysermc.org/v2/skin/decimal_part_here

Which you can use the texture id provided to get the skin from Minecraft public API
https://textures.minecraft.net/texture/texture_id_here
