### ISSUE TITLE
Player heads blurry on IPhone XR

### ISSUE THREAD

**Issue by Leonardo-Fiori** [pdinklag/MinecraftStats#113]
A player sent me this screenshot:
![image](https://user-images.githubusercontent.com/25549272/91971478-8b953c00-ed19-11ea-8ab7-c275d81c5932.png)

Looks like that player heads are upscaled using the wrong function and they loose sharp pixel edges. She didn't even notice that but I did, so i asked her device model. It's an IPhone XR.

Not a big bug of course but i though you would like to know this 😛

**Comment by pdinklag** [comment]
It's definitely not supposed to look that way. It may be that whatever browser the iPhone XR uses doesn't support the CSS that's used for pixelating, so I'll have a look at this.

Thanks for reporting!

**Comment by pdinklag** [comment]
I didn't find anything after some research.

From a technical standpoint, this is done using the [image-rendering](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering) CSS property, which supports the value `pixelated` to get a this kind of display for images. I had already included the outdated `optimizeSpeed` value to support older versions of Firefox, and I have also added a variant for old Internet Explorers now.

If it still doesn't work on an iPhone XS now, please give me some info on the browser (what browser is it and what version). My best guess is that it simply doesn't support this property and it can't be fixed unless the browser is updated.

**Comment by pdinklag** [comment]
I'm closing this now.

Unless I get details about the iPhone XR browser, I cannot look into this any further. There have been no other reports about this sort of issue, so it may be safe to assume that said browser does not (or did not, at the time of reporting) support the mentioned CSS properties.
