### ISSUE TITLE
AttributeError RecursiveNamespace config.players.showLastOnline

### ISSUE THREAD

**Issue by JeftaDirksen** [pdinklag/MinecraftStats#116]
py makeconfig.py -s D:\MyServerPath > config.json
py update.py config.json
Traceback (most recent call last):
  File "update.py", line 535, in <module>
    'showLastOnline': config.players.showLastOnline,
AttributeError: 'RecursiveNamespace' object has no attribute 'showLastOnline'

"showLastOnline" gets put in "client" but expected in "players"

https://github.com/pdinklag/MinecraftStats/blob/1594010ecfed9bc5f1d3551a3d319d178ff63b9b/mcstats/config.py#L12
https://github.com/pdinklag/MinecraftStats/blob/1594010ecfed9bc5f1d3551a3d319d178ff63b9b/update.py#L535

**Comment by pdinklag** [comment]
Whoops, yeah, that's a mistake. Thanks a lot! 👍
