### ISSUE TITLE
Updating to1.16.2

### ISSUE THREAD

**Issue by Sky-Evil** [pdinklag/MinecraftStats#121]
Hello! How about updating statistics to 1.16.2?
Many new blocks and mobs were added there.

**Comment by pdinklag** [comment]
Some snapshot added Piglin Brutes, that's covered in issue #107 .
I just had a look at the [1.16.2](https://minecraft.gamepedia.com/Java_Edition_1.16.2) and [1.16.3](https://minecraft.gamepedia.com/Java_Edition_1.16.3) wiki pages and can't really find anything else new added after 1.16?

**Comment by Sky-Evil** [comment]
Sorry if the update for 1.16.2 is already ready. How can I update it for my server? What files need to be replaced, without loss of already existing statistics.

**Comment by pdinklag** [comment]
There's a [section about it in the readme](https://github.com/pdinklag/MinecraftStats#updating-minecraftstats), you just need a git pull or, if you don't use git, re-download and overwrite all existing files. The `data` directory is not part of the repository, you don't have to delete it. And even if you did, the data itself is still present in the Minecraft server so it would be back after running an update.

**Comment by pdinklag** [comment]
Also make sure to look at [Troubleshooting](https://github.com/pdinklag/MinecraftStats#troubleshooting) if you get an "unrecognized argument" error when you run `update.py` after updating MinecraftStats. The way `update.py` is used has slightly changed and is described in the readme also.

**Comment by Sky-Evil** [comment]
I did everything I could, but I get it.
![image](https://user-images.githubusercontent.com/39336712/94682349-7c5fd900-032d-11eb-830c-d45e9819daec.png)
Config screen
![image](https://user-images.githubusercontent.com/39336712/94682424-98637a80-032d-11eb-9ae9-3957e2fb68ea.png)

Before that I downloaded all the files using the git clone command https://github.com/pdinklag/MinecraftStats.git 
and replaced them manually in my directory with old files, except for the data folder

**Comment by pdinklag** [comment]
> I did everything I could, but I get it.
> ![image](https://user-images.githubusercontent.com/39336712/94682349-7c5fd900-032d-11eb-830c-d45e9819daec.png)
> Config screen
> ![image](https://user-images.githubusercontent.com/39336712/94682424-98637a80-032d-11eb-9ae9-3957e2fb68ea.png)
> 
> Before that I downloaded all the files using the git clone command https://github.com/pdinklag/MinecraftStats.git
> And replaced them manually, deleting old files and folders except "data"

What you typed there is invalid JSON, the path needs to be in quotes (`"root/server"`).

Also, are you absolutely sure that `"root/server"` is the _full_ path to your Minecraft server - it doesn't even begin with a slash? I don't know if you have symbolic links set up locally, it's just something I noticed.

**Comment by Sky-Evil** [comment]
Oh my God! Yes, I did it!
The update was successful, thank you for telling me!

**Comment by Sky-Evil** [comment]
And one more thing. I'm trying to set up automatic updates using crontab, but it doesn't work.
I used 
*/5 * * * * python3 /home/admin/web/stats.oldcraft-mc.ru/public_html/python3 update.py config.json
as well as 
*/5 * * * * /usr/bin/python3 update.py /home/admin/web/stats/public_html/config.json
