### ISSUE TITLE
server.path not configured, please edit config

### ISSUE THREAD

**Issue by kellekerell** [pdinklag/MinecraftStats#124]
Im running into this issue when typing python3 update.py config. In the config.json Ive set everything up
`{
    "configVersion": 1,
    "database": "data",
    "server": {
        "path": "/home/amp/.ampdata/instances/Spieleaustausch/Minecraft",
        "customName": false,
        "worldName": "world"
    },`
The rest is as default... I don't know why it just won't work.

**Comment by kellekerell** [comment]
Also, there is no data folder in the main folder of the plugin... Guess that that one is only created after everything was setup successfully which it apparently isnt and I dont know why.

**Comment by kellekerell** [comment]
Thanks, thought the script would automatically use the config.json file :D Ive got another issue though. I wanted to implement a crontab task but the command just runs into the "server.path not configured" issue... The command I used is: * * * * * python3 /var/www/html/minecraft/update.py config.json

Any idea on why this doesnt work? The config.json file is configured for sure.

**Comment by kellekerell** [comment]
python3 /var/www/html/minecraft/update.py /var/www/html/minecraft/config.json prints me that the stats have been updated, but they are not.

**Comment by kellekerell** [comment]
Would this work just fine as a cronjob or are there any downsides?
`* * * * * cd /var/www/html/minecraft && update.py config.json && cd`
It seems to work but I dont know whether its clever to return back to the main directory in the end.

**Comment by pdinklag** [comment]
> Thanks for the quick reply! Thought config was just fine.
Good to know!

> Would this work just fine as a cronjob or are there any downsides?
> `* * * * * cd /var/www/html/minecraft && python3 update.py config.json && cd`

That's the common way of doing it I'd say, although maybe reconsider whether you really need an update every minute. On my own servers, I run it every 10 minutes. But that's totally your call!

> I dont know whether its clever to return back to the main directory in the end.

I don't see any reason to do it, looks like you can just as well leave that out.

**Comment by kellekerell** [comment]
Changed it to */30 for the first parameter so I get an update each half an hour, thanks for your help! Much appreciated!
