### ISSUE TITLE
Exclude UUIDs

### ISSUE THREAD

**Issue by ScottGarryFoster** [pdinklag/MinecraftStats#134]
So I want to exclude banned players and players who are alts.

We use LuckPerms and LiteBans so it's none conventional therefore I figured we'd just create a script to add these UUIDs to the config.

The config looks like this (although I've cut down the UUIDs for space)
```
{
    "configVersion": 1,
    "database": "data",
    "server": {
        "path": "/var/lib/pterodactyl/volumes/someNumber/",
        "customName": false,
        "worldName": "world"
    },
    "client": {
        "playersPerPage": 100,
        "playerCacheUUIDPrefix": 2,
        "showLastOnline": true
    },
    "players": {
        "profileUpdateInterval": 3,
        "updateInactive": false,
        "inactiveDays": 14,
        "minPlaytime": 180,
        "excludeBanned": true,
        "excludeOps": false,
        "excludeUUIDs": ["faf349cb-6b8e-404a-853a-a07f6dd9ad37","98c905a0-1b19-40d2-96cb-f426162c704f"]
    },
    "crown": {
        "gold": 4,
        "silver": 2,
        "bronze": 1
    },
    "events": []
}
```

Those two UUIDs are in the long list and yet they're still in the system:
https://stats.dominionserver.net/#player:98c905a0-1b19-40d2-96cb-f426162c704f
https://stats.dominionserver.net/#player:faf349cb-6b8e-404a-853a-a07f6dd9ad37

I edited the update.py to see if these are even coming through:
Near line 148

```
for uuid in config.players.excludeUUIDs:
    print(uuid)
    excludePlayers.add(uuid)
```
    
The UUIDs are in there

Near 476:

```
for uuid, player in players.items():
    if (not uuid in excludePlayers) and  ('last' in player) and ('name' in player) and ('stats' in player):
        validPlayers[uuid] = player
        print(uuid)
```
        
I was seeing if they made it through into this. They don't.

We are running the update every hour and I've run the update manually to check. It doesn't appear to be excluding.

How do we remove these players actively?

**Comment by pdinklag** [comment]
Hm, I'm a bit confused as to why they stay in there, especially since they seem to be handled correctly. I'll investigate on this.

As a workaround, it's safe to completely remove the `data` directory generated by Minecraft Stats: it's the same data that's on your Minecraft server, only in a different format, and the next update will completely restore it. Can you give that a try and see if the excluded players are gone then?

**Comment by pdinklag** [comment]
I moved the code handling excluded UUIDs to an earlier stage, now they should really never be considered in any case. Could you give that a try?

**Comment by ScottGarryFoster** [comment]
Sorry but that didn't work :(

However I did delete the data from one of the awards from a different player (from those two) on one of the rankings, and the data isn't coming back for that player. So it's certainly not adding data. It's just not removing data.

I can work around this by getting rid of people we add to the list everytime.

However this does seem to be a thing where it doesn't actively delete data.

**Comment by ScottGarryFoster** [comment]
We've figured it out.

So because we're running the update in a cronjob I added the full path to the update:
python3 /usr/share/MinecraftStats/update.py /usr/share/MinecraftStats/config.json

However this just doesn't seem to do anything?

I've made a bash script cd into the folder now and it'll update it. Thank you for the support!

**Comment by pdinklag** [comment]
> However this just doesn't seem to do anything?

It does, but if you don't do a `cd` first, then the working directory of the job will be the home directory of whatever user executes the job. This means you'll probably find a `data` directory there. It's not the first time this causes confusion, I'll create a followup issue.

**Comment by ScottGarryFoster** [comment]
I did find that folder in our root. Yeah something as clarification would probably help because I imagine most people will set this up with a cronjob and then seeing it's one command be tempted to attempt it with a single line.

Thank you :)
