### ISSUE TITLE
Black page

### ISSUE THREAD

**Issue by Phthisicus** [pdinklag/MinecraftStats#144]
Hi Guys,

I have a problem with running MinecraftStats. I installed a clean apache and python3.8 and i uploaded the files to the webserver.
When i want to load the page it stays black.

Anyone any ideas?

**Comment by pdinklag** [comment]
Do you mean actually black - like nothing - or the interface stuck in the loading screen?

Either way, it helps opening the script console (most browsers do that when pressing F11) and checking the *Console* for any error messages.

**Comment by pdinklag** [comment]
Closing due to lack of feedback.
