### ISSUE TITLE
Infinite loading website

### ISSUE THREAD

**Issue by kellekerell** [pdinklag/MinecraftStats#145]
I just reinstalled this application and now I have the following issue: the website seems to load infinitely (that compass). At the same time, the website loads on Microsoft Edge (cache cleared), but Chrome (cache cleared) and every other browser just shows that loading screen...

**Comment by pdinklag** [comment]
Likely some JavaScript error is occurring. Please open the developer view (F12 in Chrome) and let me know what is written in the *Console* tab. It may be even better if I could have a look at it directly, so feel free to hand me a URL to your installation here or privately (E-Mail, Discord).

(Note to self: these are the kinds of cases that I should implement #120 for.)

**Comment by pdinklag** [comment]
Closing due to lack of feedback.
