### ISSUE TITLE
'serverName' is not defined

### ISSUE THREAD

**Issue by pdinklag** [pdinklag/MinecraftStats#146]
A user reported the following error:
```
Traceback (most recent call last):
  File "update.py", line 561, in <module>
    'serverName': serverName,
NameError: name 'serverName' is not defined
```

**Comment by pdinklag** [comment]
After a brief code analysis, this should only happen if there's no custom name in the config AND no `motd` in the `server.properties`. In any event, `serverName` must be defined, so a default value should be set if it is not.

**Comment by wiktor-karczewski** [comment]
I confirm, once the empty `motd` in server.properties` was filled, problem cleared.
