### ISSUE TITLE
Negative values are possible for 'Fun Guy' award

### ISSUE THREAD

**Issue by DaMarine** [pdinklag/MinecraftStats#153]
Observe the "Fun Guy" statistic for this player: https://stats.slabserver.org/#player:e0a57633-2e22-4a35-8f23-5f922d8583ef and see that their score goes into the negatives. They therefore don't appear on the [award page for 'Fun Guy'](https://stats.slabserver.org/#award:mine_shroom)

This appears to be a similar issue to https://github.com/pdinklag/MinecraftStats/issues/126 and https://github.com/pdinklag/MinecraftStats/issues/17.

**Comment by pdinklag** [comment]
I can imagine this happens if mushrooms are collected from sources other than picking up mushrooms from forest floors or caves, e.g., via mushroom blocks or mooshrooms.

As far as I know, Minecraft doesn't count those, so maybe I can try to change this to picking up mushrooms rather than "mining" them.

**Comment by DaMarine** [comment]
Our player reckons most of their mushrooms were collected this way, but that it dropped from -4 to -132 when they placed down 2 stacks of brown mushroom. Should this really be using [StatDiffReader](https://github.com/pdinklag/MinecraftStats/blob/d72e164303c5acf1f8a618cf5fdea045ce629ab2/mcstats/mcstats.py#L29) if it's trying to calculate total mushrooms mined? Sounds like something you'd want to be calculating as a cumulative thing, and would be more consistent with other similar awards imo.

**Comment by pdinklag** [comment]
> Sounds like something you'd want to be calculating as a cumulative thing, and would be more consistent with other similar awards imo.

Yes. What I mean is that there are *picked up* stats too that count when items are picked up rather than blocks mined. That would be better, because mushrooms can be collected without breaking small mushroom blocks.

I agree that the StatDiffReader thing is a leftover here and should be removed.
