### ISSUE TITLE
Place Signs Contains Repeated Entries

### ISSUE THREAD

**Issue by blockswerker** [pdinklag/MinecraftStats#162]
The "Place Signs" award contains repeated entries. I tried regenerating the place_sign.json and it didn't help. Here's an example: https://sweetanarchy.net/playerstats/index.html#award:place_sign

Edit: Is it possible that place_sign.py is including both 'minecraft:used' and 'minecraft:sign' to create it's list instead of just the sum?

**Comment by pdinklag** [comment]
> The "Place Signs" award contains repeated entries. I tried regenerating the place_sign.json and it didn't help. Here's an example: https://sweetanarchy.net/playerstats/index.html#award:place_sign

This used to be #147 . Are you sure it wasn't fixed by the respective commit some 20 days ago?

> Edit: Is it possible that place_sign.py is including both 'minecraft:used' and 'minecraft:sign' to create it's list instead of just the sum?

No, `minecraft:sign` is a subcategory of `minecraft:used`, you can think of the nested JSON objects as "paths" to the stats.

**Comment by pdinklag** [comment]
Yeah, looks like you didn't update yet. Updating *MinecraftStats* should fix this for you.
