### ISSUE TITLE
Damage stats incorrectly parsed 

### ISSUE THREAD

**Issue by erv123** [pdinklag/MinecraftStats#163]
The stats for damage taken, blocked and dealt are parsed incorrectly, as shown in the following screenshots

![image](https://user-images.githubusercontent.com/55497525/133032257-cac7b6c2-6306-4065-9a0d-e835fb853f4c.png)

![image](https://user-images.githubusercontent.com/55497525/133032427-9f9ad824-22fc-4ed9-a6ba-15cfc9dcdd13.png)

It can be seen that on the website the first decimal place of the stat is considered as a one instead of as a decimal, which makes them all 10x their actual values.

**Comment by erv123** [comment]
examining the code it seems that the issue is the unit being set to int, but also it looks like there are no unitless stats with decimal places so i'm not sure if changing that would require more changes

**Comment by pdinklag** [comment]
Ouch, this seems bad. I'll have a closer look soon, not sure what could cause behaviour like this. The damage stats aren't particularly different from any other stats, and such code as you describe (interpreting first decimal place as 1) doesn't exist to my knowledge. The parsing of the file to JSON is done by Python, so what I could imagine is some weird localization going on.

Thanks very much for reporting!

**Comment by erv123** [comment]
i'm sure this being int has something to do with it
![image](https://user-images.githubusercontent.com/55497525/133034632-8e5f46de-f723-4a34-a2a9-39721713b89a.png)

**Comment by pdinklag** [comment]
Hm, that's only used for display in the browser. Internally, if the number has a decimal separator (`.`) in the JSON file, it should automatically be parsed and handled as a floating point value by Python, there's no explicit integer conversion there to my knowledge (I will have to check).

Could you please check one thing and look at the `data/awards/damage_dealt.json` file that MinecraftStats should have created? If the numbers in there look correct, it's only a problem displaying the value in the browser.

**Comment by erv123** [comment]
i'm not the owner of the server, but i'll ask them

**Comment by pdinklag** [comment]
OK, then maybe there are some implicit integer casts or something like that going on in the Python part. Again thanks for reporting and the feedback, I'll have a look at this!

**Comment by pdinklag** [comment]
Figured it out. Everything is OK really, all parsings are fine. I just need to introduce a new unit for damage and divide all values by 10 for display in the browser. According to [the Minecraft Wiki](https://minecraft.fandom.com/wiki/Statistics), the JSON statistics measure damage in _tenths of hearts_, which isn't respected by MinecraftStats. That explains why it's off by exactly a factor of 10.
