### ISSUE TITLE
Something seems to have gone wrong with the damage stat fix

### ISSUE THREAD

**Issue by erv123** [pdinklag/MinecraftStats#166]
![image](https://user-images.githubusercontent.com/55497525/133318438-2100cf92-4b2b-45b7-a568-5c7260394fe3.png)

**Comment by pdinklag** [comment]
Please make sure to clear the browser cache after an update so the scripts are reloaded. Unfortunately there is no way around this.

**Comment by erv123** [comment]
ok, that fixed it, thanks!
