### ISSUE TITLE
Default frontside language

### ISSUE THREAD

**Issue by MrHatter89** [pdinklag/MinecraftStats#171]
Add the configuration option that you can specify the default language of the page.
```json
{
    "language": "en",
}
```

**Comment by pdinklag** [comment]
Good call, this is still missing indeed. A special option "browser" might be added too to default to the browser language.

**Comment by pdinklag** [comment]
The configuration is done in:
```json
{
    "client": {
        "defaultLanguage": "en",
    }
}
```

I updated the documentation. Note that there is no "browser" option yet.
