### ISSUE TITLE
Winner not displaying correctly

### ISSUE THREAD

**Issue by cunhar** [pdinklag/MinecraftStats#175]
One of my events ended but it is not showing the event winner on the events list page.  It only shows Winner: "(nobody)"

https://www.hoobs.live/minecraft/#events

^-- take a loot at the beegone event

**Comment by weihao** [comment]
i am able to reproduce this error.

**Comment by weihao** [comment]
it is missing `best` field in the `summary`

**Comment by weihao** [comment]
I fixed the issue. Will submit a PR shortly.

**Comment by weihao** [comment]
Please review: https://github.com/pdinklag/MinecraftStats/pull/189

**Comment by pdinklag** [comment]
Likely fixed by #195 , would be nice if a third party could confirm this (e.g., @cunhar )?

**Comment by weihao** [comment]
yeah this is no change to the data files. just a calculation error, so you could just pull the update and let us know if it worked for you

**Comment by cunhar** [comment]
> Likely fixed by #195 , would be nice if a third party could confirm this (e.g., @cunhar )?

I can't confirm what fixed it, but it is working properly now on https://www.hoobs.live/minecraft/index.html#events after I pulled the latest master.

Thank you <3

**Comment by weihao** [comment]
@cunhar thanks 👍
