### ISSUE TITLE
Signs placed appears to be doubling up the names

### ISSUE THREAD

**Issue by ScottGarryFoster** [pdinklag/MinecraftStats#196]
For some reason the signs placed appears to be doubling up the names for us.

![image](https://user-images.githubusercontent.com/44545313/157531223-579360e2-9a87-4605-9295-f96f5dcf9ff7.png)
 Also interestingly it isn't just a visual glitch it records the people as in second place?
 
 
![image](https://user-images.githubusercontent.com/44545313/157531322-e576687d-a102-4ae0-89eb-3b7091e33ab6.png)
This is the person who was in first.

This is the link to the server: https://stats.dominionserver.net if you want to poke around.

**Comment by pdinklag** [comment]
When did you last update? This was fixed a long time ago (issue #147 ), so I want to make sure it's not back for some strange reason.

**Comment by ScottGarryFoster** [comment]
Updating fixed this issue thank you.
