### ISSUE TITLE
Stats for 1.19

### ISSUE THREAD

**Issue by pdinklag** [pdinklag/MinecraftStats#197]
With [the first 1.19 snapshot released](https://www.minecraft.net/en-us/article/minecraft-snapshot-22w11a), this issue will collect and check 1.19 related stats to be added as well as existing stats to be updated.

**Comment by DaMarine** [comment]
@pdinklag I believe all of these are complete now:




> ### New Stats
> #### Items
> * [Goat Horns](https://minecraft.fandom.com/wiki/Goat_Horn) sounded (`minecraft:goat_horn`, min data version 3093 / [22w17a](https://minecraft.fandom.com/wiki/Java_Edition_22w17a))
https://github.com/pdinklag/MinecraftStats/commit/4bd64dac689d0e17344878d6c4e176342335009a (albeit bugged, https://github.com/pdinklag/MinecraftStats/issues/206 / [MC-250943](https://bugs.mojang.com/browse/MC-250943))
> * [Recovery Compasses](https://minecraft.fandom.com/wiki/Recovery_Compass) crafted (`minecraft:recovery_compass`? min data version 3088 / [22w14a](https://minecraft.fandom.com/wiki/Java_Edition_22w14a))
https://github.com/pdinklag/MinecraftStats/commit/4bd64dac689d0e17344878d6c4e176342335009a
> 
> #### Mobs
> * [Allays](https://minecraft.fandom.com/wiki/Allay) killed (`minecraft:allay`, min data version 3085 / [22w13a](https://minecraft.fandom.com/wiki/Java_Edition_22w13a))
https://github.com/pdinklag/MinecraftStats/commit/4bd64dac689d0e17344878d6c4e176342335009a
> * [Frogs](https://minecraft.fandom.com/wiki/Frog) killed (`minecraft:frog`, min data version 3080 / [22w11a](https://minecraft.fandom.com/wiki/Java_Edition_22w11a))
https://github.com/pdinklag/MinecraftStats/commit/4bd64dac689d0e17344878d6c4e176342335009a
> * [Tadpoles](https://minecraft.fandom.com/wiki/Tadpole) killed (`minecraft:tadpole`, min data version 3080 / [22w11a](https://minecraft.fandom.com/wiki/Java_Edition_22w11a))
https://github.com/pdinklag/MinecraftStats/commit/4bd64dac689d0e17344878d6c4e176342335009a
> * [Wardens](https://minecraft.fandom.com/wiki/Warden) killed (`minecraft:warden`, min data version 3082 / [22w12a](https://minecraft.fandom.com/wiki/Java_Edition_22w12a))
https://github.com/pdinklag/MinecraftStats/commit/4bd64dac689d0e17344878d6c4e176342335009a
> 
> ### Changes to existing stats
> #### Items / Blocks
> * Add [Mangrove Log](https://minecraft.fandom.com/wiki/Log) (`minecraft:mangrove_log`?) to `mine_wood` award.
Shouldn't need updates, `+_log` wildcard in [mine_wood.py](https://github.com/pdinklag/MinecraftStats/blob/4192280dd03721a30f645aec13947d9fb82c5d84/mcstats/stats/mine_wood.py) takes care of  new`mangrove_log` block
> * Add [Mangrove Propagule](https://minecraft.fandom.com/wiki/Sapling) (`minecraft:mangrove_propagule`) to `place_sapling` award.
https://github.com/pdinklag/MinecraftStats/commit/eb069f16478d77607a1a57310660cc6e32087a61
> * Add [Mud](https://minecraft.fandom.com/wiki/Mud) (`minecraft:mud`) to `mine_ground` award.
https://github.com/pdinklag/MinecraftStats/commit/1e1d41090dbee64a66029389133c1783ca4cbc05
> * Add [Mud](https://minecraft.fandom.com/wiki/Mud) (`minecraft:mud`) to `use_dirt` award.
https://github.com/pdinklag/MinecraftStats/commit/1e1d41090dbee64a66029389133c1783ca4cbc05

**Comment by pdinklag** [comment]
Yes I believe so, thanks for summing these up!
The goat horn bug is on Mojang's end, nothing I can fix. I'll close this one now.
