### ISSUE TITLE
Some stats have stat.unit.tenths_of_heart

### ISSUE THREAD

**Issue by ScottGarryFoster** [pdinklag/MinecraftStats#199]
(Apologise if this is already an issue, I did search)

I'm on the latest version (updated this morning) and have seen on Berserk, Ouch and Shield the words: "stat.unit.tenths_of_heart" after the number:
![image](https://user-images.githubusercontent.com/44545313/159457864-218a3b6f-4426-443a-9048-0308a8a4e020.png)
![image](https://user-images.githubusercontent.com/44545313/159457906-7deab8e6-afe5-41f7-82f6-038efde9e97c.png)

Link to our page here: https://stats.dominionserver.net/#award:damage_taken

Is this our stats files? or something on the stats software?

**Comment by pdinklag** [comment]
Hey,
as far as I know, this has only been reported in Discord once and never here, so it's good to have it as reference.

This is a browser cache issue: after updating from a version that didn't have the `stat.unit.tenths_of_heart`, this happens until the browser decides to actually reload the English localization files. Clearing the browser cache and reloading the page should solve the problem, I'm afraid there is no other fix for this.
