### ISSUE TITLE
'EventStat' object has no attribute 'webranking'

### ISSUE THREAD

**Issue by Prof-Bloodstone** [pdinklag/MinecraftStats#202]
Running latest script freshly without the `data/` dir existing results in:
```python
Traceback (most recent call last):
  File "<PATH>/update.py", line 489, in <module>
    event.webranking = sorted(event.webranking, key = lambda i: i['value'], reverse=True)
AttributeError: 'EventStat' object has no attribute 'webranking'
```
Looks like https://github.com/pdinklag/MinecraftStats/commit/2ae7aee2ec77c41ca79bb597b9944a3d249a1487 might have broken it, since `EventStat` only has `ranking`: https://github.com/pdinklag/MinecraftStats/commit/2ae7aee2ec77c41ca79bb597b9944a3d249a1487

I can confirm that running global replace `s/webranking/ranking/g` on the update script results in no errors from the script.

Let me know if I should PR this as fix :)

**Comment by pdinklag** [comment]
> Running latest script freshly without the `data/` dir existing results in:
> 
> ```python
> Traceback (most recent call last):
>   File "<PATH>/update.py", line 489, in <module>
>     event.webranking = sorted(event.webranking, key = lambda i: i['value'], reverse=True)
> AttributeError: 'EventStat' object has no attribute 'webranking'
> ```

That's not good, I'll have a look.

> Looks like [2ae7aee](https://github.com/pdinklag/MinecraftStats/commit/2ae7aee2ec77c41ca79bb597b9944a3d249a1487) might have broken it, since `EventStat` only has `ranking`: [2ae7aee](https://github.com/pdinklag/MinecraftStats/commit/2ae7aee2ec77c41ca79bb597b9944a3d249a1487)
> 
> I can confirm that running global replace `s/webranking/ranking/g` on the update script results in no errors from the script.

That sounds like a bad idea, because that commit fixed the ranking display being outdated. This bug should be fixed, probably by initializing the webranking as empty when it doesn't exist.
