### ISSUE TITLE
Goat horn stat not working

### ISSUE THREAD

**Issue by braydofficial** [pdinklag/MinecraftStats#206]
The minecraft.used:minecraft.goat_horn does not work in the current version of Minecraft, due to a bug directly in Minecraft where the stat is not updating.
Because of that the advancement in this project will also not update at the moment.

This is caused by Minecraft bug MC-250943 as described here: https://bugs.mojang.com/browse/MC-250943

**Comment by pdinklag** [comment]
Thanks for the report; I'll leave the stat in anyway for now, usually Mojang fix these kinda bugs fast enough.

**Comment by pdinklag** [comment]
Apparently, this has been fixed. Could anybody confirm whether the award is now working?

**Comment by pdinklag** [comment]
Confirmed to work by now.
