### ISSUE TITLE
Missing Polish Language

### ISSUE THREAD

**Issue by Dominikodz** [pdinklag/MinecraftStats#214]
Hey! Remember when I posted Polish translation in December? Well, I kinda don't see it :( I don't have time to check what's happening but i can assure you it's not showing up.
I did everything properly while adding translation 
![obraz](https://user-images.githubusercontent.com/64926921/223554693-9c38c8fd-6ac7-4f2f-8411-243220b68287.png)
I can give you my site http://ip27.vs5.titanaxe.com/ currently its not working due to nginx problems but I git pulled latest version

**Comment by pdinklag** [comment]
Ow, that's because you did change the JavaScript properly, but the minified version wasn't updated. I'll fix that soon!

**Comment by pdinklag** [comment]
Fixed in v3.0.0.
Note that the browser cache may have to be cleared after updating.
