### ISSUE TITLE
Player name cannot be displayed properly using MultiLogin

### ISSUE THREAD

**Issue by MingriLingran** [pdinklag/MinecraftStats#241]
[MultiLogin](https://github.com/CaaMoe/MultiLogin)
It is a plug-in that allows genuine players and skin station players to enter the game at the same time. However, when exporting data, the names of players who use the skin station to enter cannot be displayed normally.
![4U5IUB9F_ 2RX8{$H(_FK`9](https://github.com/pdinklag/MinecraftStats/assets/99112592/ba0e4433-79d9-4a98-97f7-116e42e71da6)
Is there any solution?

**Comment by pdinklag** [comment]
From just a screenshot, I cannot tell what's wrong. I would have to get a look at the UUIDs of the affected and what Mojang's API returns for them. Please send me a link to your *MinecraftStats* installation via Discord or E-Mail so I can have a look.

**Comment by pdinklag** [comment]
As mentioned, I cannot do anything with just a screenshot. Closing due to lack of feedback.
