### ISSUE TITLE
all stats have nobody as best

### ISSUE THREAD

**Issue by filip2cz** [pdinklag/MinecraftStats#244]
In my website, all stats have nobody as best even if there are two players active:
main page: https://stats.ssfs.fkomarek.eu/#awards
stats of one active player: https://stats.ssfs.fkomarek.eu/#player:2d3a0328-fdef-405e-9007-93ecdfa4ebe5

**Comment by pdinklag** [comment]
Hi!

What also feels very off is that in the list of players, there are two players listed but the heading says 0 players (0 active, 0 inactive). It seems to me that something is wrong with the generated data, as if though they were generated by different updates.

Could you try to delete the generated `data` directory and run the updater again *only once* and check the result then?

**Comment by filip2cz** [comment]
It was actually my bad, wrong config file.
Thanks and sorry for issue
