### ISSUE TITLE
[Question] moved path, partial available data

### ISSUE THREAD

**Issue by bmhm** [pdinklag/MinecraftStats#28]
Hi!

I'd like to use this python script with my dockerized minecraft (my github repo yet to be updated).

Differences: 
* My maps are in a subfolder named "maps", not in the main server directory. It's a separate docker volume.
* the config files are just symlinks to `$SERVER_DIR/config/<filename>`, so I can have the config as a seperate volume as well.
* The server is spigot, not vanilla.

Now, obviously, I cannot mount the whole Spigot Server into the MinecraftStats container. But I could mount the config (including players, etc.) and the maps.

Would that suffice?

Thanks and best regards,
Ben

**Comment by pdinklag** [comment]
The only potential issue with Spigot / Multiworld is in case it keeps track of individual stats per world. That's not supported, of course, and I have no intentions as of right now to support it, but I'm also not aware that happens or is even possible.

For the main world path (the one that contains the stats), that's what `-w` is intended for indeed. You can also avoid the `server.properties` access if you use `--server-name="My Server"` or something in the command line. The properties file is only used as a convenience to get the name from the MOTD.
