### ISSUE TITLE
Website stuck on "Loading"

### ISSUE THREAD

**Issue by gorillaback** [pdinklag/MinecraftStats#36]
The python script retrives the player data and I've confirmed it does upload json files, however the website does not seem to be receiving any data. I cloned the GIT project so I have not moved any files around.

**Comment by pdinklag** [comment]
So there is a `data` directory that contains a `db.json.gz` file and subdirectories?

If that's the case, I need some more info to debug. Is there any error message in the browser console? In most browsers, you can hit F12 to go in developer mode and find a "Console" tab. If there are any errors, those will help me find the cause.

Alternatively, if your page is public, you can give me the link and I can check for myself from a client-side perspective.

**Comment by gorillaback** [comment]
Hey, apologizes had some time off.
It seems as the issue is the delay on updating the website.
If the last update was on may 17th and I update today, it seems to take a long time to update.
Any idea why?

**Comment by gorillaback** [comment]
Apologies for the late reply.
Thank you, seems like I had some CORS issue.
