### ISSUE TITLE
Jumps statistic incorrect

### ISSUE THREAD

**Issue by AidanSkerry** [pdinklag/MinecraftStats#38]
[jump.jy](https://github.com/pdinklag/MinecraftStats/blob/master/mcstats/stats/jump.py) should use statistic

> minecraft:jump

rather than 

> minecraft:fall_one_cm

**Comment by pdinklag** [comment]
Ouch!
That explains the large numbers - thanks for reporting!

**Comment by AidanSkerry** [comment]
No worries.
I was wondering how I was jumping upwards of 6 times a second for over 50 hours, was rather confused until I found this!
