### ISSUE TITLE
Electrician counting redstone_ore as mined

### ISSUE THREAD

**Issue by AidanSkerry** [pdinklag/MinecraftStats#40]
Unsure why, but this causes the award stat to go negative very quickly.
Easy to replicate by modifying save data.

**Comment by pdinklag** [comment]
Hm. May be that I understand Python's matching the wrong way?
It does try to match `minecraft:redstone`, which is a prefix of `minecraft:redstone_ore`. This may be the issue here. Possibly something like `minecraft:redstone$` is needed.

**Comment by AidanSkerry** [comment]
Not entirely sure, not well versed with python myself, but that does seem the most likely cause.

**Comment by pdinklag** [comment]
Aye, confirmed by this little test:
```py
import re

def find_match(p, subjects):
    print('"{}" matches ...'.format(p))
    pc = re.compile(p)
    for s in subjects:
        if pc.match(s):
            print('\t' + s)

subjects = ['redstone', 'redstone_ore']
find_match('redstone', subjects)
find_match('redstone$', subjects)
```

Result:
```
"redstone" matches ...
        redstone
        redstone_ore
"redstone$" matches ...
        redstone
```

Will fix - probably by auto-inserting `$` at the end of each pattern, because that's really what's intended.

**Comment by AidanSkerry** [comment]
Cheers mate, good stuff.
