### ISSUE TITLE
Updating Skins Fails

### ISSUE THREAD

**Issue by geekrawker** [pdinklag/MinecraftStats#44]
Only issue I'm having with the past 2 updates is "Failed to update skins".   All new players on the board show only default skins.
![Screen Shot 2019-05-31 at 12 48 21 AM](https://user-images.githubusercontent.com/47543024/58684409-cf8ed980-833d-11e9-8c27-33cc098e2078.png)
![Screen Shot 2019-05-31 at 12 48 41 AM](https://user-images.githubusercontent.com/47543024/58684445-e33a4000-833d-11e9-8f40-de09df096e9b.png)

**Comment by pdinklag** [comment]
What do you mean by "past 2 updates"? Updates of MinecraftStats, or updates of Minecraft?

Nothing changed regarding skins in this project, so this would be important to know. If Mojang changed something about how the skins are retrieved, that would explain.

**Comment by pdinklag** [comment]
OK, just tried and it is working fine on my side, so we can exclude a change on Mojang's side.

I will make a commit in a few minutes that prints a few more details about why it failed, because I need some more detailled info here.

**Comment by geekrawker** [comment]
ah, downloaded one of the -master zip's a few months back, but didn't apply it to the 1.13 sever.  

Getting the 1.14 version of our server ready 3 weeks ago and started using that particular download.   No custom skins loaded (no big deal still prepping the server),  noticed you all posted some changes the past couple days and we are close to releasing our 1.14 server.   Unpacked the latest  zip and re-ran the typical update.py command.     Still No joy.   

Possible you are correct about Mojang

**Comment by pdinklag** [comment]
Try again wtih the updated script, hopefully it gives some hints as to what's wrong.

**Comment by geekrawker** [comment]
Thanks -   I'm getting 2 different errors now.  

1)  (using only your new update.py) "updating skin for Nicoli ...
failed to update skin for Nicoli
global name 'urllib' is not defined"

Then tried replacing the entire -Master folder with a fresh download... now i get this error:

2) "Traceback (most recent call last):
  File "update.py", line 14, in <module>
    import mojang
  File "--removed my server path--MinecraftStats-master\mojang.py", line 3, in <module>
    import urllib.request
ImportError: No module named request

**Comment by geekrawker** [comment]
Solved,  Python 2.7 is not compatible with urllib.request in the Mojang.py.    
Tried to use urllib2, but simply updating to python 3.8 resolved the issue.   Thanks for printing the error, would have never noticed it was my python version.  :D 👍
