### ISSUE TITLE
Question: Is there a list of stats that can be used?

### ISSUE THREAD

**Issue by lukeeexd** [pdinklag/MinecraftStats#49]
Trying to add new stats, like spawners broken, scaffolding placed etc etc, wondering if theres a list from minecraft that can be used. Also will 1.14 blocks work e.g scaffolding ?

**Comment by pdinklag** [comment]
You can write a Python module for any stat that Minecraft collects. Just create one in the `mcstats/stats` directory. It's easiest to use the existing ones for reference, e.g. copy one that is closely related and change it to your needs.

The only list I know of is this: https://minecraft.gamepedia.com/Statistics

Other statistics are mob kills, blocks mined, etc for each type. Take a look a the existing modules and player statistic JSON files too, they give good hints as to what's there.

**Comment by lukeeexd** [comment]
Yeah I've been adding ones by using template of others. Just havent seen one about breaking spawners so don't know how I'd add it

**Comment by pdinklag** [comment]
Well, you'll have to find the block ID for spawners. The Minecraft Wiki has this kind of information, so that's the go-to reference.

**Comment by lukeeexd** [comment]
Oh so i can literally do `mcstats.StatReader(['minecraft:mined','minecraft:monster_spawner']),` ?

**Comment by pdinklag** [comment]
If `minecraft:monster_spawner` is the correct ID, yep, that's it! I believe it's just `minecraft:spawner`, but you can double-check that.

**Comment by lukeeexd** [comment]
Yep that worked. Do you know if theres one for words said?

**Comment by pdinklag** [comment]
Not that I know of. I guess those kinds of stats would be listed under that Wiki page I linked.

Anyway, feel free to create pull requests for new stats, always good to get fresh ideas. Didn't think about spawners myself, it's a good one! :+1:

**Comment by lukeeexd** [comment]
How do I pull request?

**Comment by pdinklag** [comment]
Never mind if it's too much of a hassle, I will probably incorporate those awards myself.
