### ISSUE TITLE
Endermite stats are working in 1.8.7

### ISSUE THREAD

**Issue by Ubiquitous-X** [pdinklag/MinecraftStats#5]
The tracking of killing endermite is working as intended.
https://bugs.mojang.com/browse/MC-33710

Confirmed working on my Spigot 1.8.7 installation with MinecraftStats

**Comment by pdinklag** [comment]
Ah, thanks for the info!
I prefer enabling stats in blocks of four so the alignment fits, so I'll keep this in mind next time!

You can use the Endermite stat right away, though, as I'm sure you've figured out. Simply uncomment the stat definition.

**Comment by Ubiquitous-X** [comment]
Ah yes, I fixed it on my setup. Was only giving a heads up.
Btw, it is a really lovely little script you have here. So well written code and everything is made logic, and perfect for customizing!
Currently feeding the json files to the webserver with rsync. Heyo DigitalOcean!
