### ISSUE TITLE
Newbie Question: how to run update.py

### ISSUE THREAD

**Issue by mechcalvin** [pdinklag/MinecraftStats#51]
My minecraft server is from one host, and my website server is from another.

I copy all file to domain.com/stats

where and how do i run the update.py script from my website host? and /path/to/server as ip:port?

**Comment by pdinklag** [comment]
> and /path/to/server as ip:port?

No, MinecraftStats only works with files. I'm not sure it's even possible to retrieve stat data any other (feasible) way.

> where and how do i run the update.py script from my website host?

That's something you have to figure out by yourself, sorry.

If you do not have any shell access to execute commands on your website host, what you can do is run the script on your Minecraft server machine and copy the generated `data` directory to your website host (e.g. your "domain.com/stats" directory).

**Comment by mechcalvin** [comment]
Thanks!
