### ISSUE TITLE
Cant make glass broken

### ISSUE THREAD

**Issue by lukeeexd** [pdinklag/MinecraftStats#55]
Trying to track all glass blocks and glass panes broken. Trying to use other stats as templates but just cant get it to work. Could you help?

```python
from mcstats import mcstats
mcstats.registry.append(
    mcstats.MinecraftStat(
        'break_glass',
        {
            'title': 'Glassbreaker',
            'desc': 'Glass broken',
            'unit': 'int',
        },
        mcstats.StatSumMatchReader(
            ['minecraft:mined'],
            ['minecraft:glass','minecraft:.*stained_glass']),
            ['minecraft:glass','minecraft:.*glass_pane']),
    ])
))
```

**Comment by pdinklag** [comment]
Well, your syntax is broken and I believe you're using `StatSumMatchReader` wrong. First is a path (which is `minecraft:mined`), second is _one_ array of patterns to match.

Try it like this:
```py
from mcstats import mcstats
mcstats.registry.append(
    mcstats.MinecraftStat(
        'break_glass',
        {
            'title': 'Glassbreaker',
            'desc': 'Glass broken',
            'unit': 'int',
        },
        mcstats.StatSumMatchReader(
            ['minecraft:mined'],
            ['minecraft:glass','minecraft:.*glass_pane','minecraft:.*stained_glass']),
    ])
))
```

It also appears that stained glass is midding from my "place glass" stat, eh?

**Comment by lukeeexd** [comment]
> ```python
> from mcstats import mcstats
> mcstats.registry.append(
>     mcstats.MinecraftStat(
>         'break_glass',
>         {
>             'title': 'Glassbreaker',
>             'desc': 'Glass broken',
>             'unit': 'int',
>         },
>         mcstats.StatSumMatchReader(
>             ['minecraft:mined'],
>             ['minecraft:glass','minecraft:.*glass_pane','minecraft:.*stained_glass']),
>     ])
> ))
> ```

Using that gives. And yes it is missing from place glass :P
`Traceback (most recent call last):
  File "update.py", line 17, in <module>
    from mcstats.stats import *
  File "/home/www/html/stats/mcstats/stats/break_glass.py", line 13
    ])
    ^
SyntaxError: invalid syntax
minecraft@TWS:~/scripts$
`

**Comment by pdinklag** [comment]
Yeah that whole line needs to be gone.
Updated my previous reply.

**Comment by lukeeexd** [comment]
> Yeah that whole line needs to be gone.
> Updated my previous reply.

Yeah that worked. How would I add stained glass to the place_glass stat?

**Comment by pdinklag** [comment]
Same way, add `'minecraft:.*stained_glass'` to the stat reader's second array.
Will open an issue and fix it soon.

**Comment by lukeeexd** [comment]
> Same way, add `'minecraft:.*stained_glass'` to the stat reader's second array.
> Will open an issue and fix it soon.

tyty
