### ISSUE TITLE
No module named mcstats

### ISSUE THREAD

**Issue by CatPasswd** [pdinklag/MinecraftStats#57]
Spanking new server setup, from bare metal. I configured a spigot server, installed the FAMP stack, and python3. Attempting to run update.py throws an error:

root@minecraft:/usr/local/www/apache24/data/MinecraftStats # python3 update.py -s /home/minecraft/spigot/
Traceback (most recent call last):
  File "update.py", line 16, in <module>
    from mcstats import mcstats
ModuleNotFoundError: No module named 'mcstats'
root@minecraft:/usr/local/www/apache24/data/MinecraftStats # python3 --version
Python 3.6.8

Any suggestions would be appreciated. I don't speak python and can't even make a guess.

**Comment by pdinklag** [comment]
Hm, it's pretty hard to make a guess here actually.

You did clone the entire MinecraftStats there and not _just_ `update.py`, right? Like, there is that directory `mcstats` with a `mcstats.py` file in it?

**Comment by CatPasswd** [comment]
I downloaded a zip, and put all the extracted files into the directory, yes.
root@minecraft:/usr/local/www/apache24/data/MinecraftStats # ls -la
total 49
drwxr-xr-x  3 root  wheel    10 Jul  8 17:22 .
drwxr-xr-x  3 root  wheel     5 Jul  8 17:18 ..
-rw-r--r--  1 root  wheel   960 Jul  8 17:18 LICENSE.txt
-rw-r--r--  1 root  wheel  8967 Jul  8 17:18 README.md
drwxr-xr-x  2 root  wheel     3 Jul  8 17:22 __pycache__
-rw-r--r--  1 root  wheel  3993 Jul  8 17:18 index.html
-rw-r--r--  1 root  wheel   694 Jul  8 17:18 mojang.py
-rw-r--r--  1 root  wheel   799 Jul  8 17:19 mojang.pyc
-rw-r--r--  1 root  wheel  2804 Jul  8 17:18 style.css
-rwxr-xr-x  1 root  wheel  9982 Jul  8 17:18 update.py

**Comment by pdinklag** [comment]
If that's the full file listing, you are missing the `mcstats` directory for sure! In fact, I don't see any subdirectories in your listing, so I don't think you copied everything. Try a recursive copy that also takes the subdirectories.

**Comment by CatPasswd** [comment]
Ugh. I'm an idiot. You're right, I didn't add a -r to my mget 

Fixed now. Thanks for the help.

**Comment by pdinklag** [comment]
In the end it's good it was just that, you're welcome! 👍
