### ISSUE TITLE
Request: Add numbers beside people in /players

### ISSUE THREAD

**Issue by lukeeexd** [pdinklag/MinecraftStats#60]
https://i.imgur.com/LbsdaAW.png which updates if you select show inactive players

**Comment by pdinklag** [comment]
Any specific reason for needing a number besides every player name? The order is alphabetical, so not sure what the goal is.

Do you want to know how _many_ players there are on your server? Sounds like a good idea, but then, one number on top should suffice, right?

**Comment by lukeeexd** [comment]
> Any specific reason for needing a number besides every player name? The order is alphabetical, so not sure what the goal is.
> 
> Do you want to know how _many_ players there are on your server? Sounds like a good idea, but then, one number on top should suffice, right?

Yeah maybe not a number beside everyone. Yeah just a total number somewhere. So like total for active then when you display inactive people it would change to include that. I'm able to find the total players on my server but because I have a min time for peoples stats to show id like to know the difference between the total and stats displaying players I have

**Comment by lukeeexd** [comment]
https://tws-mc.com/stats/#players tyty :D
