### ISSUE TITLE
update.py failing to parse json without play_one_minute

### ISSUE THREAD

**Issue by blockbandit** [pdinklag/MinecraftStats#68]
If a player joins a server and disconnects quickly, their stats json file lacks a "play_one_minute" entry which causes update.py to fail when attempting to parse this file.

Contents of such a json file:

{"stats":{"minecraft:custom":{"minecraft:leave_game":1}},"DataVersion":1631}

**Comment by pdinklag** [comment]
Should be fixed, thanks for reporting! 😄
