### ISSUE TITLE
Spelling error on stat

### ISSUE THREAD

**Issue by Ubiquitous-X** [pdinklag/MinecraftStats#7]
`config-stats.php` line 190 I believe has a spelling error
From:
`safeGet('stat.useItem.minecraft.cooked_fished', $json, 0) +`
To:
`safeGet('stat.useItem.minecraft.cooked_fish', $json, 0) +`
to display proper stats in the "Fish Gourmet" achivement

**Comment by pdinklag** [comment]
Confirmed. Will update soon with the first 1.9 features. Thanks for reporting!
