### ISSUE TITLE
Minplaytime not working?

### ISSUE THREAD

**Issue by lukeeexd** [pdinklag/MinecraftStats#70]
Have min playtime set to 60mins. 953 unique people joined my server, Stats show 953 people joined also "Showing 953 players ( 355 active, 598 inactive)." but all 953 100% wouldnt have played 60mins so why is 953 people displayed on the stats?

``python3.6 update.py -s /home/minecraft/backup/survival --server-name "The Wooden Spoon SMP" --min-playtime 60``

**Comment by pdinklag** [comment]
May be related to #41.
I randomly clicked a bunch of your inactive players and while most did indeed play more than 60 minutes, some pages didn't load.

It may be fixed by the changes I did for #65, where I'm still waiting for some feedback.

**Comment by lukeeexd** [comment]
Ah makes sense, ty
