### ISSUE TITLE
Webpage not displaying any Stats, but does show HOF

### ISSUE THREAD

**Issue by OfficialTehlo** [pdinklag/MinecraftStats#71]
So I was just installing this on my server, and the webpage etc works.
https://stats.hydrovanillasmp.com/

It shows the style, etc, and HOF works because it displays my players etc but it doesn't show the main stats. It keeps updating forever.

The error I'm getting in the console of my Browser is this:
`Uncaught SyntaxError: Unexpected token ! in JSON at position 79
    at JSON.parse (<anonymous>)
    at Object.successFunc (mcstats-start.js:14)
    at mcstats-loader.js:50
    at XMLHttpRequest.req.onload (mcstats-loader.js:26)`

Thanks in advance for the help! Love your product that you've made and would love to fully use it for my Members :)

**Comment by OfficialTehlo** [comment]
Also where do I make it so the favicon uses my Server Icon? :)

**Comment by pdinklag** [comment]
Hey!
Looking at that error position it seems like it has trouble to use your server's name.

Did you use the `--server-name` flag for `update.py`? If not, what is your MOTD in the `server.properties`?

> Also where do I make it so the favicon uses my Server Icon? :)

That's already working, isn't it? 😄

**Comment by OfficialTehlo** [comment]
Thanks for the fast response!

`python3 update.py -s /home/minecraft/multicraft/servers/server1` is what I used to run it.

My MOTD in server properties is 
`\u00A7b\u00A7lHydro\u00A79 \u00A7lVanilla SMP\u00A7b |\u00A7c \u00A7lSeason 4\!\n\u00A77Apply at \u00A78https\://hydrovanillasmp.com/`

Which looks like this:
https://gyazo.com/05951c273d967bb72f7f70c87f887a2d

Also the favicon isn't working for me (yet)
The page looks like this for me:
https://gyazo.com/e23bd621af02e0f4837fe9b762fdefa1

**Comment by pdinklag** [comment]
> `python3 update.py -s /home/minecraft/multicraft/servers/server1` is what I used to run it.
Alright.

> My MOTD in server properties is
> `\u00A7b\u00A7lHydro\u00A79 \u00A7lVanilla SMP\u00A7b |\u00A7c \u00A7lSeason 4\!\n\u00A77Apply at \u00A78https\://hydrovanillasmp.com/`

Hm... is there a specific reason for the many backslashes? `\!` and `\:` are causing the problems for sure. The question is why did you escape them? Is that somehow required for those symbols to work in the MOTD?

> Also the favicon isn't working for me (yet)

Strange, displays fine for me here. 🤔

**Comment by OfficialTehlo** [comment]
> Hm... is there a specific reason for the many backslashes? \! and \: are causing the problems for sure. The question is why did you escape them? Is that somehow required for those symbols to work in the MOTD?

Thats how the color codes are built up for the MOTD. I thought that was the only way of doing it for MOTD in server properties because you cant use the &6 tag for colors there.
Could I set my Server Name manually for MCStats?

> Strange, displays fine for me here. 🤔

Yeah one of my Members just told me it works for them aswell, so no worries on that! :)

**Comment by pdinklag** [comment]
> Thats how the color codes are built up for the MOTD. I thought that was the only way of doing it for MOTD in server properties because you cant use the &6 tag for colors there.

The color codes are the `\u00A7` things - they should work fine with mcstats. The colon and exclamation marks should not be escaped - e.g. use just `:` instead of `\:` and `!` instead of `\!`. I'm not exactly sure why Minecraft itself accepts them.

In any event, you could add `--server-name "§b§1Hydro§9 Vanilla SMP"` to your `update.py` and that should do the trick?

**Comment by OfficialTehlo** [comment]
Okay so I ran `python3 update.py -s /home/minecraft/multicraft/servers/server1 --server-name "§b§1Hydro§9 Vanilla SMP"` and it gave me no errors after returning, but didn't show me anything else either. What's next? :)

**Comment by pdinklag** [comment]
Well the site seems to be working fine now!

**Comment by OfficialTehlo** [comment]
It indeed seems to be working, and I've already added a few more own Statistics! Thanks a lot for the fast support and help :)

You have created something amazing, shame so little people know about it because this is a key feature for SMP Servers! :)

**Comment by pdinklag** [comment]
Thanks!
And no worries - judging by the support requests in the past two months, it seems to be getting more popular! Thanks for using!
