### ISSUE TITLE
Report of MinecraftStats usage

### ISSUE THREAD

**Issue by lukeeexd** [pdinklag/MinecraftStats#73]
https://www.spigotmc.org/resources/web-icarey-net-whitelist-system.8157/ is using your stats inside his plugin. Not sure you know or if its allowed so just putting this here

**Comment by pdinklag** [comment]
It is allowed to use but they removed any and all references to this original project, which pretty much violates my only license requirement. I'll give them a few days to maybe realize this, otherwise I'll send them a note this week.

Thanks!

**Comment by pdinklag** [comment]
Added some clarifications in 7476f8e7007329d8b3776fcaf186e0fec9838edc and filed [an issue in their Github repository](https://github.com/smashedbotatos/iCarey_Whitelist_System/issues/1).
