### ISSUE TITLE
Offline users are not included in stats

### ISSUE THREAD

**Issue by woduda** [pdinklag/MinecraftStats#79]
Offline users are ignored in stats processing. It's caused by getting player name only from Mojang service (online/premium player). But if the player is offline then the `continue` statement is reached:
https://github.com/pdinklag/MinecraftStats/blob/7476f8e7007329d8b3776fcaf186e0fec9838edc/update.py#L210

**Comment by pdinklag** [comment]
What do you mean by "offline"?

That `continue` line is reached only if Mojang returns an empty profile for a UUID. If that's the case, the player is invalid. I don't know when it happens, but then it's a bug on Mojang's side or the account is deleted or doesn't exist for other reasons. It has nothing to do with "offline".

**Comment by woduda** [comment]
Offline = cracked/non-premium player. That kind of player doesn't have Mojang account but can play on servers with `online-mode` set to `false`.

**Comment by pdinklag** [comment]
I see, never thought of that to be honest.

OK, well, their profile is retrieved from the Mojang servers because that's how I find out their player name and skin. Player name can be retrieved from the server's player cache, so that could be solved.

I suppose "non-premium" players are unable to use skins? So that wouldn't matter anyway.

**Comment by pdinklag** [comment]
Can you give the [`offline_players`](https://github.com/pdinklag/MinecraftStats/compare/offline-players) branch a try? It should use the `usercache.json` file of your server to lookup offline players.

**Comment by woduda** [comment]
Change from offine_players has reverted my stats to previous state where offline users are also included. Thanks for fix

**Comment by pdinklag** [comment]
Good to know, I'll merge it into the master then. Thanks! :+1:
