### ISSUE TITLE
Special characters in server.properties.motd cause loading failure

### ISSUE THREAD

**Issue by ColinHaley** [pdinklag/MinecraftStats#80]
I've only tested so far with an exclamation point, but I am working under the assumption it may be similar for other special characters due to forced escape characters "\" in MOTD field.

Works: motd=test
Broken: motd=test\!

**Comment by pdinklag** [comment]
You mean the site being stuck at "Loading" in the browser, right?
Looks like I need to reconsider how it's parsed into the client. :roll_eyes: Thanks for reporting!

**Comment by cunhar** [comment]
This is still breaking with \n in the MOTD i added a quick sting replace before the json.parse

**Comment by pdinklag** [comment]
Yes, there is a new open issue on it (#94).
