### ISSUE TITLE
Edit crown scores 

### ISSUE THREAD

**Issue by minster586** [pdinklag/MinecraftStats#82]
I want to be able to edit the scores for points on getting gold award and so forth

**Comment by pdinklag** [comment]
You're right, there should be command-line parameters for this.

For now, you can do it by changing this line:
https://github.com/pdinklag/MinecraftStats/blob/bd9ef52b4345a2fe2ad2086a6e3ef199fb750d28/mcstats/mcstats.py#L183

`score[1]` is gold, `score[2]` is silver and `score[3]` is bronze, `score[0]` is the final crown score.

**Comment by pdinklag** [comment]
You can now use `--crown-gold`, `--crown-silver` and `--crown_bronze` in the command line to customize the crown scores.
