### ISSUE TITLE
stat "kill_bee" is not supported by server version 1976 (required: 2200)

### ISSUE THREAD

**Issue by CatPasswd** [pdinklag/MinecraftStats#91]
After updating the MinecraftStats package, the webpage stopped loading the data. It sits with the compass icon spinning and a "Loading" message displayed. Running the update script manually gives the following error messages

stat "kill_bee" is not supported by server version 1976 (required: 2200)
stat "use_honey_bottle" is not supported by server version 1976 (required: 2200)

I've since upgraded my server from 1.14.4 to 1.15.1 and the same message persists. 

I'm now running the most recent paper version
[07:02:39 INFO]: This server is running Paper version git-Paper-33 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
[07:02:39 INFO]: Checking version, please wait...
[07:02:40 INFO]: Previous version: git-Paper-237 (MC: 1.14.4)
[07:02:40 INFO]: You are running the latest version

**Comment by pdinklag** [comment]
I will be able to look into this only in a few days. As a workaround, you can simply delete the affected statistics scripts (py files) to get it back running.

**Comment by pdinklag** [comment]
Hm, would you like to update on this, does it still happen?

In 1.14.4, the message was completely correct.
After upgrading to 1.15.1, however, did you ever join the server?

Unfortunately, Minecraft does not save the server version anywhere, so MinecraftStats finds out by looking at the highest `DataVersion` of any player. So even after you upgraded, if nobody ever logged in and out of the updated server, MinecraftStats will still only recognize the last version.

I believe this is the issue, would you be able to confirm this by trying again?

**Comment by CatPasswd** [comment]
The error no longer shows up when the script is run. It must be as you say, a one-time error after upgrading the server and I ran the script manually without having anyone log in.

However, there are zero awards showing now. See http://nix.catpasswd.net/MinecraftStats

**Comment by pdinklag** [comment]
I'm closing this because the title issue has been resolved, see #94 for the new issue.
