### ISSUE TITLE
Statistics do not work

### ISSUE THREAD

**Issue by Sky-Evil** [pdinklag/MinecraftStats#92]
Hello, the statistics were installed on my server, but it doesn’t work, at the beginning it showed nicknames of the players who went to the server, but now it has completely stopped and is not updating, I can’t understand what the problem is(
https://stats.oldcraft-mc.ru/
My server is on version 1.15.1 paper

**Comment by pdinklag** [comment]
Sorry I'm currently travelling and couldn't have a look at it yet. It seems like you got it to work? Do you know what the issue is or was?

**Comment by Sky-Evil** [comment]
Hi, yes, my friend was able to solve this problem. It seems that the error was that I did not correctly indicate the server name when running statistics)

**Comment by pdinklag** [comment]
OK, thanks for reporting it anyway! :smile:
