### ISSUE TITLE
Server name cannot contain newlines

### ISSUE THREAD

**Issue by pdinklag** [pdinklag/MinecraftStats#94]
[...] there are zero awards showing now. See http://nix.catpasswd.net/MinecraftStats

_Originally posted by @CatPasswd in https://github.com/pdinklag/MinecraftStats/issues/91#issuecomment-577325975_

**Comment by pdinklag** [comment]
I checked using Chrome's debugging function and it appears your server name / MOTD contains a newline and MinecraftStats can't handle that.

I'll fix that in the future, but for now you'll have to use `--server-name "NIX"` or something to override that.

**Comment by CatPasswd** [comment]
That argument did indeed fix it. Thanks.

**Comment by pdinklag** [comment]
Thanks for confirming!
