### ISSUE TITLE
Awards not loading

### ISSUE THREAD

**Issue by mindtrick27** [pdinklag/MinecraftStats#97]
So I've installed MinecraftStats. My issue is the main page never loads. If you click on players or HOF it displays the data with no issues, but if you click on the actual players name it shows no awards, and if you click onto the awards page it also shows nothing. 

I apologize in advance if this has been answered somewhere else, I could not find anything to help me out.

http://104.243.37.234/MinecraftStats-master/

**Comment by mindtrick27** [comment]
had a new line in the motd, removed and was fixed

**Comment by pdinklag** [comment]
Thanks for reporting and glad you could fix.
I'll just link #94 here, seems like I really need to fix it soon.
